#!/usr/bin/env node
/**
 * build-b2a.cjs — B2a 미러 컨피규레이터 생성기
 *
 * 무엇: 라이브 컨피규레이터(public/index.html)에서 Cowork 프로젝트 문서용 미러
 *       (dist/b2a-configurator.html)를 생성한다.
 * 왜:   미러를 손으로 복사해 유지하면 라이브와 조용히 어긋난다(과거 "B2a 미러 스왑"
 *       수작업이 매번 붙어 다녔다). 결정 #29 "복사가 아니라 생성" 을 미러에도 적용.
 *
 * 미러가 라이브와 달라야 하는 지점은 딱 하나 — 가이드 URL.
 * 프로젝트 문서/아티팩트로 열리면 옆에 guide.html 이 없으므로 상대경로가 죽는다.
 * 그래서 절대 URL 로 바꾸고, iframe 이 샌드박스에 막히거나 아직 배포 전(404)일 때를
 * 대비해 ① 헤더의 새 탭 링크 ② iframe 아래 상시 안내 바를 함께 넣는다.
 * (감지식이 아니라 "상시" 인 이유는 T5 주석 참고 — 실패를 감지할 방법이 없다.)
 *
 * 산출물은 두 곳에 게시된다. 둘은 별개 저장소이므로 반드시 함께 교체할 것:
 *   ① 프로젝트 문서 `claude/b2a-configurator.html`  (Projects project_write)
 *   ② Cowork 아티팩트 `b2a-configurator`            (SendUserFile → update_artifact)
 * ①만 바꾸면 아티팩트 갤러리에서 여는 사람에게는 옛 버전이 계속 보인다.
 *
 * 사용: node scripts/build-b2a.cjs          → dist/b2a-configurator.html 생성
 *       node scripts/build-b2a.cjs --check  → 드리프트 검사(CI). 어긋나면 exit 1
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'public', 'index.html');
const OUT = path.join(ROOT, 'dist', 'b2a-configurator.html');
const LIVE = 'https://greeny-ds.vercel.app';
const GUIDE_URL = LIVE + '/guide.html';

const BANNER =
  '<!-- AUTO-GENERATED by scripts/build-b2a.cjs — 직접 수정 금지. 원천은 public/index.html -->\n' +
  '<!-- B2a 미러: 가이드 iframe 만 절대 URL(' + GUIDE_URL + ')로 스왑된 사본 -->';

/** 정확히 1회만 등장해야 하는 치환. 아니면 하드 실패(원천이 바뀐 걸 조용히 넘기지 않는다). */
function swap(s, from, to, label) {
  const n = s.split(from).length - 1;
  if (n !== 1) {
    console.error(`build-b2a: [${label}] 주입 지점이 ${n}개입니다(1개여야 함). public/index.html 이 바뀌었는지 확인하세요.`);
    console.error(`  찾던 문자열: ${JSON.stringify(from.slice(0, 90))}`);
    process.exit(1);
  }
  return s.replace(from, to);
}

function build() {
  if (!fs.existsSync(SRC)) {
    console.error('build-b2a: public/index.html 이 없습니다.');
    process.exit(1);
  }
  let s = fs.readFileSync(SRC, 'utf8');

  // 원천에 가이드 진입점이 살아 있는지 먼저 확인 — 없으면 미러를 만들 이유가 없다.
  const nGuide = s.split('data-guide').length - 1;
  if (nGuide < 10) {
    console.error(`build-b2a: 원천의 data-guide 진입점이 ${nGuide}개뿐입니다(상단 1 + 딥링크 9 = 10 이상 기대).`);
    process.exit(1);
  }

  // T1 — 생성물 배너
  s = swap(s, '<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER, 'T1 배너');

  // T2 — 미러임을 상단 태그에 표시
  s = swap(s,
    '<span class="tag">내부 베타 v1.3.2 — Apple 워싱 · KDX 어휘 정렬(border) · 컴포넌트 스튜디오</span>',
    '<span class="tag">내부 베타 v1.3.2 — Apple 워싱 · KDX 어휘 정렬(border) · 컴포넌트 스튜디오 · B2a 미러</span>',
    'T2 미러 태그');

  // T3 — 폴백/새 탭 링크 CSS
  s = swap(s,
    '  .gdrawer iframe{flex:1;width:100%;border:0;display:block}',
    '  .gdhead .gdnew{font-size:10.5px;color:var(--brand);text-decoration:none;border:1px solid var(--line);\n' +
    '    border-radius:6px;padding:3px 8px;white-space:nowrap}\n' +
    '  .gdhead .gdnew:hover{border-color:var(--brand);background:var(--brand050)}\n' +
    '  .gdrawer iframe{flex:1;width:100%;border:0;display:block}\n' +
    '  .gdfall{flex:none;display:flex;align-items:center;gap:8px;padding:9px 14px;\n' +
    '    border-top:1px solid var(--line);background:var(--brand050);font-size:11px;color:var(--muted)}\n' +
    '  .gdfall .gfb{margin-left:auto;font-size:11px;font-weight:700;color:var(--brand);\n' +
    '    border:1px solid var(--line);border-radius:7px;padding:5px 10px;text-decoration:none;white-space:nowrap}\n' +
    '  .gdfall .gfb:hover{border-color:var(--brand);background:#fff}',
    'T3 안내 바 CSS');

  // T4 — 드로어 헤더: 새 탭 링크 추가 + 부제 갱신
  s = swap(s,
    '    <span class="gdsub">정본 1부 · 갱신되면 여기도 함께 최신</span>\n',
    '    <span class="gdsub">정본 1부 · 갱신되면 여기도 함께 최신</span>\n' +
    '    <a class="gdnew" id="gNew" href="' + GUIDE_URL + '" target="_blank" rel="noopener">새 탭에서 열기 ↗</a>\n',
    'T4 새 탭 링크');

  // T5 — iframe 뒤에 상시 안내 바
  //   자동 감지를 쓰지 않는 이유: 404 페이지도 CSP 차단 프레임도 iframe 의 load 이벤트를
  //   그대로 발생시키고, 교차 출처라 contentDocument 를 들여다볼 수도 없다. 즉 "실패"를
  //   신뢰성 있게 감지할 방법이 없다. 그래서 감지 대신 상시 노출 — 어떤 실패 모드에서도 옳다.
  s = swap(s,
    '  <iframe id="gFrame" title="Core System 개념 가이드"></iframe>',
    '  <iframe id="gFrame" title="Core System 개념 가이드"></iframe>\n' +
    '  <div class="gdfall" id="gFall">\n' +
    '    <span>위가 비어 보이면 문서 샌드박스가 프레임을 막은 경우입니다 — 정본은 항상 여기서 열립니다.</span>\n' +
    '    <a class="gfb" href="' + GUIDE_URL + '" target="_blank" rel="noopener">새 탭에서 열기 ↗</a>\n' +
    '  </div>',
    'T5 안내 바');

  // T6 — 상대경로 → 절대 URL. 딥링크 해시는 새 탭 링크에도 함께 전달한다.
  s = swap(s,
    "      fr.src='guide.html'+hash; fr.dataset.loaded='1'; fr.dataset.hash=hash;",
    "      fr.src=GUIDE_URL+hash; fr.dataset.loaded='1'; fr.dataset.hash=hash;\n" +
    "      fb.href=GUIDE_URL+hash; nw.href=GUIDE_URL+hash;",
    'T6 절대 URL 스왑');

  // T7 — 스크립트 상단 변수
  s = swap(s,
    "  var dim=document.getElementById('gDim'), dr=document.getElementById('gDrawer'), fr=document.getElementById('gFrame');",
    "  var GUIDE_URL='" + GUIDE_URL + "';\n" +
    "  var dim=document.getElementById('gDim'), dr=document.getElementById('gDrawer'), fr=document.getElementById('gFrame');\n" +
    "  var fb=document.querySelector('#gFall .gfb'), nw=document.getElementById('gNew');",
    'T7 링크 변수');

  return { html: s, bytes: Buffer.byteLength(s, 'utf8'), entries: nGuide };
}

const { html, bytes, entries } = build();

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  const ok = cur === html;
  console.log(`build-b2a --check: b2a ${ok ? 'OK' : 'DRIFT'} · 진입점 ${entries}개 · ${bytes} bytes`);
  if (!ok) {
    console.error('build-b2a: dist/b2a-configurator.html 이 public/index.html 과 어긋납니다. `node scripts/build-b2a.cjs` 로 재생성하세요.');
    process.exit(1);
  }
  process.exit(0);
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, html);
console.log(`build-b2a: public/index.html → dist/b2a-configurator.html · 진입점 ${entries}개 · ${bytes} bytes`);
