#!/usr/bin/env node
/*
 * build-css.cjs — primitive DTCG 토큰 → CSS 변수 + flat JSON (공식 빌드)
 *
 * 무엇: tokens/tokens.primitive.json 의 모든 $value 리프를 경로-kebab 이름으로 평탄화해
 *       build/css/primitives.css 와 build/json/primitives.flat.json 을 생성한다.
 * 왜:   외부 의존(Style Dictionary/네트워크) 없이 CI에서 항상 재현·검증 가능한 자립 빌더
 *       (상호운용 런 #4에서 값 기준 diff=0 확인된 산출 형식을 그대로 유지).
 * 사용: node scripts/build-css.cjs            # build/ 에 생성
 *       node scripts/build-css.cjs --check    # 생성물이 커밋본과 동일한지 검증(비생성)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
// 기본은 SSOT primitive. env로 커스텀 primitive·출력 디렉터리 지정 가능(config 재생성용).
const SRC = process.env.PRIMITIVE_PATH ? path.resolve(process.cwd(), process.env.PRIMITIVE_PATH) : path.join(ROOT, 'tokens', 'tokens.primitive.json');

const kebab = (s) =>
  String(s).replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Z])([A-Z][a-z])/g, '$1-$2').toLowerCase();

// DTCG 트리 → [ [name, value], ... ] (깊이우선, 키 삽입순)
function flatten(node, prefix, out) {
  if (node && typeof node === 'object' && Object.prototype.hasOwnProperty.call(node, '$value')) {
    out.push([prefix.join('-'), node.$value]);
    return;
  }
  if (node && typeof node === 'object') {
    for (const k of Object.keys(node)) {
      if (k.startsWith('$')) continue; // $description 등 메타 스킵
      flatten(node[k], prefix.concat(kebab(k)), out);
    }
  }
}

// CSS 값 직렬화: 단순값은 그대로, 복합 $value(폰트 패밀리 배열·그림자 객체 배열)는 CSS 문자열로
function cssValue(v) {
  if (Array.isArray(v)) {
    if (v.length === 0) return 'none'; // elevation-0
    if (v[0] && typeof v[0] === 'object') {
      // 그림자 레이어: offsetX offsetY blur spread color, 레이어는 ", " 결합
      return v.map((s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`).join(', ');
    }
    // 폰트 패밀리 문자열 배열: 공백 포함 항목만 따옴표, ", " 결합
    return v.map((x) => (/\s/.test(x) ? `"${x}"` : x)).join(', ');
  }
  return v;
}

function build() {
  const T = JSON.parse(fs.readFileSync(SRC, 'utf8'));
  const pairs = [];
  for (const k of Object.keys(T)) {
    if (k.startsWith('$')) continue;
    flatten(T[k], [kebab(k)], pairs);
  }
  const css =
    '/* AUTO-GENERATED by scripts/build-css.cjs — 직접 수정 금지. 원천은 tokens/*.json */\n' +
    ':root {\n' +
    pairs.map(([n, v]) => `  --${n}: ${cssValue(v)};`).join('\n') +
    '\n}\n';
  // flat JSON도 CSS와 동일한 직렬화 문자열 저장(복합값 포함)
  const flat = '{\n' + pairs.map(([n, v]) => `  ${JSON.stringify(n)}: ${JSON.stringify(cssValue(v))}`).join(',\n') + '\n}\n';
  return { css, flat, count: pairs.length };
}

const OUT_BASE = process.env.BUILD_DIR ? path.resolve(process.cwd(), process.env.BUILD_DIR) : path.join(ROOT, 'build');
const CSS_OUT = path.join(OUT_BASE, 'css', 'primitives.css');
const JSON_OUT = path.join(OUT_BASE, 'json', 'primitives.flat.json');

const { css, flat, count } = build();

if (process.argv.includes('--check')) {
  // 값 기준 비교(헤더 주석 줄 제외): 커밋본과 토큰 값이 동일한지
  const strip = (s) => s.replace(/^\/\*[^\n]*\*\/\n/, '');
  const curCss = fs.existsSync(CSS_OUT) ? strip(fs.readFileSync(CSS_OUT, 'utf8')) : '';
  const genCss = strip(css);
  const curFlat = fs.existsSync(JSON_OUT) ? fs.readFileSync(JSON_OUT, 'utf8') : '';
  const cssOk = curCss === genCss;
  const flatOk = curFlat === flat;
  console.log(`build-css --check: css ${cssOk ? 'OK' : 'DRIFT'} · flat ${flatOk ? 'OK' : 'DRIFT'} · ${count} tokens`);
  if (!cssOk || !flatOk) process.exit(1);
  process.exit(0);
}

fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });
fs.mkdirSync(path.dirname(JSON_OUT), { recursive: true });
fs.writeFileSync(CSS_OUT, css);
fs.writeFileSync(JSON_OUT, flat);
console.log(`build-css: ${count} tokens → build/css/primitives.css, build/json/primitives.flat.json`);
