#!/usr/bin/env node
/*
 * build-guide.cjs — 개념 가이드 정본 → 컨피규레이터용 배포본 (공식 빌드)
 *
 * 무엇: docs/service-concept-guide.html(정본, 손으로 갱신되는 단 하나의 원천)을 읽어
 *       ① 컨피규레이터 복귀 스트립 ② 스트립 높이 보정 CSS ③ iframe 임베드 모드 스크립트
 *       를 주입한 public/guide.html 을 생성한다. 본문은 한 글자도 바꾸지 않는다.
 * 왜:   가이드를 컨피규레이터에 "복사해 넣지" 않기 위해서. 사본은 언제나 생성물이고,
 *       정본이 갱신되면 이 스크립트만 다시 돌리면 된다. --check 가 CI에서 사본 표류를 막는다.
 * 사용: node scripts/build-guide.cjs            # public/guide.html 생성
 *       node scripts/build-guide.cjs --check    # 생성물이 커밋본과 동일한지 검증(비생성)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'docs', 'service-concept-guide.html');
const OUT = path.join(ROOT, 'public', 'guide.html');

const BANNER =
  '<!-- AUTO-GENERATED by scripts/build-guide.cjs — 직접 수정 금지. 원천은 docs/service-concept-guide.html -->';

// 스트립 높이(px). CSS 보정·scroll-margin 계산의 단일 출처.
const BAR = 44;

function build() {
  let s = fs.readFileSync(SRC, 'utf8');

  // ── 1. 버전 도장 파싱 (없으면 하드 실패: 정본이 아닌 파일을 배포하지 않도록)
  const m = s.match(/개념 가이드 v(\d+\.\d+) · (\d{4}-\d{2}-\d{2})/);
  if (!m) {
    console.error('build-guide: 정본에서 버전 도장(개념 가이드 vX.Y · YYYY-MM-DD)을 찾지 못했습니다. 중단합니다.');
    process.exit(1);
  }
  const [, ver, date] = m;

  // ── 2. 주입 지점 존재 확인 (정본 구조가 바뀌면 조용히 깨지지 않게)
  for (const anchor of ['<!DOCTYPE html>', '</head>', '<body>', '</body>']) {
    if (s.indexOf(anchor) === -1) {
      console.error(`build-guide: 정본에서 주입 지점 '${anchor}' 를 찾지 못했습니다. 중단합니다.`);
      process.exit(1);
    }
  }

  // ── 3. 생성물 표식
  s = s.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER);

  // ── 4. 스트립 높이 보정 CSS (본문 CSS는 건드리지 않고 뒤에서 덮어씀)
  const css = `<style>
  /* ↓ build-guide.cjs 주입: 컨피규레이터 복귀 스트립(${BAR}px) 보정 */
  .gbar{position:sticky;top:0;z-index:200;height:${BAR}px;display:flex;align-items:center;gap:10px;
    padding:0 16px;background:#fff;border-bottom:1px solid #e2e5ea;font-size:12px;
    font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Pretendard','Noto Sans KR',sans-serif}
  .gbar a.gback{display:inline-flex;align-items:center;gap:5px;color:#1c1e21;text-decoration:none;
    font-weight:600;border:1px solid #e2e5ea;border-radius:8px;padding:6px 11px;background:#fff}
  .gbar a.gback:hover{border-color:#725cd3;color:#725cd3}
  .gbar .gsp{margin-left:auto;display:flex;align-items:center;gap:9px}
  .gbar .gver{font-family:var(--mono);font-size:11px;color:#5f6672;background:#f4f5f7;
    border:1px solid #e2e5ea;border-radius:6px;padding:3px 8px;white-space:nowrap}
  .gbar a.gnew{color:#725cd3;text-decoration:none;font-weight:600;white-space:nowrap}
  .gbar a.gnew:hover{text-decoration:underline}
  body.gembed .gback{display:none}
  body:not(.gembed) .gnew{display:none}
  /* 사이드바·앵커가 스트립 아래로 숨지 않도록 */
  .sidenav{top:${BAR}px;max-height:calc(100vh - ${BAR}px)}
  @media(max-width:1139px){.sidenav{top:${BAR}px}}
  .part,section,.card,.role{scroll-margin-top:${BAR + 16}px}
</style>
`;
  s = s.replace('</head>', css + '</head>');

  // ── 5. 복귀 스트립 (정본에는 없는, 배포본에서만 붙는 크롬)
  const bar = `
<div class="gbar">
  <a class="gback" href="index.html">← 컨피규레이터로</a>
  <div class="gsp">
    <span class="gver">개념 가이드 v${ver} · ${date}</span>
    <a class="gnew" href="guide.html" target="_blank" rel="noopener">새 탭에서 열기 ↗</a>
  </div>
</div>`;
  s = s.replace('<body>', '<body>' + bar);

  // ── 6. 임베드 모드 판별 (컨피규레이터 슬라이드오버 iframe 안이면 복귀 링크 대신 새 탭 링크)
  const js = `<script>
/* build-guide.cjs 주입: iframe 임베드 모드 */
(function(){
  var embedded = false;
  try { embedded = window.self !== window.top; } catch(e) { embedded = true; }
  if (embedded) {
    document.body.classList.add('gembed');
    var n = document.querySelector('.gbar .gnew');
    if (n) n.addEventListener('click', function(){ /* 현재 스크롤 위치 해시를 그대로 전달 */
      n.href = 'guide.html' + (location.hash || '');
    });
  }
})();
</script>
`;
  s = s.replace('</body>', js + '</body>');

  return { html: s, ver, date, bytes: Buffer.byteLength(s, 'utf8') };
}

const { html, ver, date, bytes } = build();

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  const ok = cur === html;
  console.log(`build-guide --check: guide ${ok ? 'OK' : 'DRIFT'} · v${ver} (${date}) · ${bytes} bytes`);
  if (!ok) {
    console.error('build-guide: public/guide.html 이 정본과 어긋납니다. `node scripts/build-guide.cjs` 를 실행해 재생성하세요.');
    process.exit(1);
  }
  process.exit(0);
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, html);
console.log(`build-guide: v${ver} (${date}) → public/guide.html · ${bytes} bytes`);
